### ISSUE TITLE
Attachment indicator without attachment

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#557]
## What
Sometimes I received an email with no attachments but there is the indication: "1 attachment"
This happens because Leap identifies the pgp-keys mimetype and automatically import the key, leaving no attachments but the indication that there's one on the message.

<img width="674" alt="screen shot 2015-12-17 at 2 07 29 pm" src="https://cloud.githubusercontent.com/assets/2657059/11874569/958bbdaa-a4c7-11e5-9ef4-eaa6f0f5eeef.png">

## Definition of done
When leap processes a key, we don't show that there is an attachment.

**Comment by pereiragislene** [comment]
I tested sending emails with attachment from Apple Mail to Pixelated and I noticed that none of them displayed the link for downloading the attachments. It's only possible to see the attachments count.

I sent the same files (.pdf and .jpeg) from Gmail (web version) to Pixelated and I was able to see the links.

In both cases, when inspecting the attachments array in the javascript, I was able to find them and by going to [pixelated-url]/attachment/[attachment-ident], I could download them, but was not able to read them properly. I could only read the PGP signature file content.

 It seems we are not handling fine the way Apple Mail attaches the files and need to investigate more. @giovaneliberato tried sending from Thunderbird and it worked fine. We also need to check what happens when the mail comes from Outlook.

**Comment by pereiragislene** [comment]
New findings:
1. On leap_mailstore.py: there's a method (_extract_filename) that gets the attachment filename via regex. I noticed that the content disposition from Apple Mail is sent like this example: u'attachment;\n\tfilename=some_file.rtf' and the REGEX is expecting double quotes around the filename, i.e.: u'attachment; filename="some_file.rtf"'. We need to fix the REGEX to be able to get attachments from Apple Mail.
2. On leap_maistore.py: there's a method (_extract_part_map) that checks if content_disposition has the word "attachment". In case we receive an inline attachment, it won't be captured because of that. We need to check for both "attachment" and "inline".

**Comment by pereiragislene** [comment]
Problems No. 1 and 2 (described above) were fixed. I've created the issue #562 to fix the 3rd one (inline attachment).

**Comment by fbernitt** [comment]
The problem described by @re-nobre still exists. I sent a signed mail with my public key as an attachment of type application/pgp-keys to my pixelated account. This is how the UI looked like:

![screenshot_-_key_and_signature](https://cloud.githubusercontent.com/assets/108677/12117353/90a5bec8-b3c0-11e5-8419-fcbf07c11e4b.png)

**Comment by fbernitt** [comment]
Pushed 9db569e3f5170efd852322d428b9b0282c7bb114 as a fix.

**Comment by re-nobre** [comment]
Hey, @fbernitt!
I sent an email (without attachments) from wazokazi to staging to see what happens.
On staging, I received an email with 2 attachments and now I can saw the files (one is my public key and another is my signature).

![screen shot 2016-01-12 at 11 57 43 am](https://cloud.githubusercontent.com/assets/2657059/12265439/2f08eef6-b924-11e5-8b67-3cfaaa0f2e21.png)

I noticed 3 other issues in this situation:
1 - The signature wasn't processed
3 - The public key wasn't processed
2 - The public key file continues as "unnamed"

**Comment by re-nobre** [comment]
I will close this issue and talk with LEAP folks about these 3 issues.
