### ISSUE TITLE
Protect against Cross-Site-Request-Forgery

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#612]
Currently we are not protecting our requests against XSRF attacks. 

Example html that makes use of xsrf to trigger a logout in the user agent:

```html
<html>
<body>
  <img src="https://localhost:8080/auth/logout" /><!-- dispatcher setup -->
  <img src="https://localhost:3333/logout" /><!-- user-agent setup -->
  <img src="https://mail.wazokazi.is/auth/logout" /><!-- wazokazi.is dispatcher setup -->
</body>
</html>
```

Just put this in a file or just click [this link to logout](https://rawgit.com/fbernitt/a270b79479d03596b780/raw/61d5bb545700a356382668e0971458a85f79cf69/logout.html).

**Comment by pereiragislene** [comment]
It's working fine :+1:

**Comment by felixhammerl** [comment]
clicking logout on wazokazi does this:
![screen shot 2016-02-29 at 6 08 06 pm](https://cloud.githubusercontent.com/assets/1818340/13402271/d9822bde-df0f-11e5-9e23-f5b433d2be68.png)

**Comment by pereiragislene** [comment]
When clicking the logout button on Wazokazi, I saw: "403: Forbidden"

When testing locally pointing to dev environment, I got:

"405 - Method Not Allowed
Your browser approached me (at /logout) with the method "GET". I only allow the methods HEAD, POST here."

**Comment by mnandri** [comment]
I pushed a fix in dispatcher for wazokazi, which checks the presence of a valid csrf token before allowing logout in the dispatcher mode. 
To QA: you need to do a post without csrf token as a form input (from a REST client for example -- or use the example @fbernitt put above), it should throw a 403 still... whereas the regular logout functionality on the logout button in wazokazi should still work.

On local/dev, please force reload the page (CMD +R), I suspect the reason for the 405 is that we have disabled logout using GET at the backend but the frontend was not updated to use the new "POST" for the logout...
Otherwise, please run on debug mode and screenshot both the backend and client, if the error could be reproduced. I'm moving it back to QA for now.

**Comment by pereiragislene** [comment]
Hey @mnandri, we've upgraded the dispatcher version on Wazokazi, but I'm still getting 403: Forbidden.
Could you please check? Thanks.

**Comment by pereiragislene** [comment]
As reference, this is the commit on the dispatcher: https://github.com/pixelated/pixelated-dispatcher/commit/56f04cf11f2960a976e100c4875310e13c963056

**Comment by mnandri** [comment]
the problem is that dispatcher also has its own xsrf protection so the post on logout never actually reaches the post handler...
I have disabled it... so now should be okay.

**Comment by pereiragislene** [comment]
I've checked Wazokazi. The logout button is working again, but it's possible to log the user out by doing a GET request to https://mail.wazokazi.is/auth/logout.

**Comment by mnandri** [comment]
Yes, we intentionally left GET to work, on purpose, as it will take more effort to disable it... and given, we are removing the dispatcher architecture imminently, disabling GET is no longer a priority or a wasted effort.
So closing this issue for now.
